language: go
go:
  - 1.11.x
  - 1.12.x
before_install:
  - go get -u honnef.co/go/tools/cmd/staticcheck
script: make vet staticcheck test
env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org
cache:
  directories:
    - $GOPATH/pkg/mod
